# -*- coding: utf-8 -*-
"""2.URL's

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6X9nmSgM_wvuJkjtBWjbZncyU4x0Guh
"""

import requests
from requests.exceptions import RequestException, HTTPError
from bs4 import BeautifulSoup
import time

def download_urls(urls):
    max_retries = 3
    results = {}

    for url in urls:
        retry_count = 0
        success = False
        error_message = None

        while retry_count < max_retries and not success:
            try:
                response = requests.get(url, timeout=5)  # Set timeout to 5 seconds
                response.raise_for_status()  # Raise an exception for bad responses (4xx or 5xx)

                soup = BeautifulSoup(response.content, 'html.parser')
                text_content = soup.get_text(separator='\n')

                results[url] = text_content.strip()  # Strip leading/trailing whitespace
                success = True
            except HTTPError as e:
                error_message = f"HTTP error occurred: {str(e)}"
            except RequestException as e:
                error_message = f"RequestException occurred: {str(e)}"
                retry_count += 1
                print(f"Failed to download {url}. Retrying ({retry_count}/{max_retries})...")
                time.sleep(1)  # Wait for 1 second before retrying
            except Exception as e:
                error_message = f"Unexpected error occurred: {str(e)}"
                retry_count += 1
                print(f"Failed to download {url}. Retrying ({retry_count}/{max_retries})...")
                time.sleep(1)  # Wait for 1 second before retrying

        if not success:
            results[url] = f"Failed to download: {error_message}"

    return results

# Example usage:
if __name__ == "__main__":
    urls = [
        "https://example.com",
        "https://nonexistenturl.com",
        "https://www.google.com"
    ]

    results = download_urls(urls)

    for url, content in results.items():
        print(f"URL: {url}")
        print(f"Content:")
        print(content)
        print()

