# -*- coding: utf-8 -*-
"""4.Python_DF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xiBCUtAJ-rUFePFF3LS4v8apBcKFMak
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder

def preprocess_data(df):
    categorical_cols = df.select_dtypes(include=['object']).columns
    label_encoders = {}
    for col in categorical_cols:
        label_encoders[col] = LabelEncoder()
        df[col] = label_encoders[col].fit_transform(df[col])

    df.fillna(df.mean(), inplace=True)
    numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns
    scaler = StandardScaler()
    df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

    return df, scaler, label_encoders

if __name__ == "__main__":
    data = {
        'Name': ['Alice', 'Bob', 'Charlie', 'Dave', 'Eve'],
        'Age': [25, 30, None, 35, 20],
        'Gender': ['Female', 'Male', 'Male', 'Male', 'Female'],
        'Salary': [50000, 60000, 55000, None, 48000]
    }
    df = pd.DataFrame(data)

    preprocessed_df, scaler, label_encoders = preprocess_data(df)

    print("Preprocessed DataFrame:")
    print(preprocessed_df)

