# -*- coding: utf-8 -*-
"""5.Fibanocci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uM0-_bbIrto8mnCNdYoXT5Hjj_q33XwE
"""

def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)

if __name__ == "__main__":
    n = int(input("Enter a non-negative integer to compute its Fibonacci number: "))
    result = fibonacci(n)
    print(f"The {n}th Fibonacci number is: {result}")

