# -*- coding: utf-8 -*-
"""6.Divide

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5_Ee1y5raxA6ry-sisD3bWbBVngAUzZ
"""

def divide_numbers(dividend, divisor):
    if divisor == 0:
        return "Error: Division by zero is not allowed"
    else:
        return dividend / divisor

if __name__ == "__main__":
    dividend = float(input("Enter the dividend: "))
    divisor = float(input("Enter the divisor: "))

    result = divide_numbers(dividend, divisor)
    print(f"Result of {dividend} divided by {divisor} is: {result}")

